language: node_js
node_js: node
os:
  - linux
  - windows
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - dpkg
      - fakeroot
before_install:
  - npm i -g npm
  - npm --version
before_deploy:
  - npm install -g @electron-forge/cli
  - npm run make
deploy:
  provider: releases
  file_glob: true
  file: out/make/*
  overwrite: true
  skip_cleanup: true
  prerelease: true
  draft: true
