key: ""
username: ""
saveDirectory: "%DOC%/Files"
logFile: "%DOC%/out.log"
overwriteExisting: true
useCache: true
skipFlash: false
skipVideo: false
globalBlacklistNoticeShown: false
analytics: "PROMPT"
analyticsId: null
blacklistedTags: []
threads: 3
