key: ""
username: ""
saveDirectory: "%CONFIG%/Files"
logFile: "%CONFIG%/out.log"
overwriteExisting: true
useCache: true
skipFlash: false
skipVideo: false
analytics: "PROMPT"
analyticsId: null
blacklistedTags: []
