name: e621downloader
title: E621 Downloader
version: "git"
summary: Bulk image downloader for e621.
description: Bulk image downloader for e621.
grade: devel
confinement: strict
icon: src/assets/icons/png/256x256.png
license: MIT
type: "app"
base: core20
parts:
  my-part:
    plugin: nil
