name: Electron Builder

on: push

jobs:
  ubuntu:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -D
      - run: npm run make:linux
      - uses: actions/upload-artifact@v2
        with:
          name: e621downloader.deb
          path: out/make/deb/x64/*
  # windows:
  #   name: Windows Build
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 15.x
  #     - run: npm i -D
  #     - run: npm run make:win32
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: e621downloader.exe
  #         path: out/make/squirrel.windows/x64/E621Downloader.Setup.exe
  # mac-os:
  #   name: MacOS Build
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 15.x
  #     - run: npm i -D electron-installer-dmg appdmg nan
  #     - run: npm run make:darwin
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: e621downloader.dmg
  #         path: out/make/*
