name: Electron Builder

on: push

jobs:
  ubuntu:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -D
      - run: npm run make:linux
      - uses: actions/upload-artifact@v2
        with:
          name: e621downloader.deb
          path: out/make/deb/x64/*
